# Generated by Django 4.1 on 2024-06-15 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_profit', models.CharField(default='0.00', max_length=255)),
                ('total_deposit', models.CharField(default='0.00', max_length=255)),
                ('btc_balance_equivalent', models.CharField(blank=True, default='0.00', max_length=255, null=True)),
                ('account_balance', models.CharField(default='0.00', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
