# Generated by Django 4.1 on 2024-06-15 19:26

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('wallet_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_plan', models.CharField(choices=[('STARTER PLAN', 'STARTER PLAN'), ('PREMIUM PLAN', 'PREMIUM PLAN'), ('SIX MONTHS PLAN', 'SIX MONTHS PLAN'), ('PARTNERSHIP', 'PARTNERSHIP')], default='CLASSIC', max_length=255)),
                ('amount_in_USD', models.IntegerField()),
                ('investment_status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED')], default='Pending', max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.crypto')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='None', max_length=255)),
                ('account_number', models.IntegerField(default=0)),
                ('routine_number', models.IntegerField(default=0)),
                ('ssn', models.IntegerField(default=0)),
                ('id_front', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('id_back', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('amount_in_USD', models.IntegerField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_profit', models.CharField(default='0', max_length=255)),
                ('total_deposit', models.CharField(default='0', max_length=255)),
                ('btc_balance_equivalent', models.CharField(blank=True, max_length=255, null=True)),
                ('wallet_address', models.CharField(default='---', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=256)),
                ('postal_code', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='None', max_length=255)),
                ('account_number', models.IntegerField(blank=True, null=True)),
                ('routine_number', models.IntegerField()),
                ('ssn', models.IntegerField()),
                ('id_front', cloudinary.models.CloudinaryField(max_length=255)),
                ('id_back', cloudinary.models.CloudinaryField(max_length=255)),
                ('amount_in_USD', models.IntegerField()),
                ('withdrawal_status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED')], default='Pending', max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradingOptionsChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tradingoptions')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenshotOFPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('investment_connected', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.investment')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crypto_Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_gateway', models.CharField(choices=[('BITCOIN', 'BITCOIN'), ('ETHEREUM', 'ETHEREUM')], default='Bitcoin', max_length=255)),
                ('amount_in_USD', models.IntegerField()),
                ('wallet_address', models.CharField(default='null', max_length=400)),
                ('tan_code', models.IntegerField(blank=True, null=True)),
                ('withdrawal_status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED')], default='Pending', max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Profile image')),
                ('id_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ID image')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField()),
                ('account_status', models.CharField(choices=[('NOT VERIFIED', 'NOT VERIFIED'), ('VERIFIED', 'VERIFIED')], default='Not Verified', max_length=255)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verify', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
