# Generated by Django 5.2.4 on 2025-10-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0004_alter_investment_options_alter_investment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether')], max_length=10)),
                ('network', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet address',
                'verbose_name_plural': 'Wallet addresses',
                'ordering': ('asset', 'network'),
                'unique_together': {('asset', 'network')},
            },
        ),
    ]
