# Generated by Django 5.2.4 on 2025-09-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_deposit_investment_withdrawal_delete_preregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='PaymentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether')], max_length=10)),
                ('network', models.CharField(blank=True, choices=[('Bitcoin', 'Bitcoin'), ('ERC-20', 'ERC-20'), ('TRC-20', 'TRC-20')], max_length=20)),
                ('address', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('asset', 'network'),
                'unique_together': {('asset', 'network')},
            },
        ),
    ]
