# Generated by Django 5.2.4 on 2025-10-16 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_deposit_reference_alter_investment_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['user', 'status'], name='app_deposit_user_id_180647_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['created_at'], name='app_deposit_created_b65ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'status'], name='app_investm_user_id_c5468e_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['created_at'], name='app_investm_created_ba7b65_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['user', 'status'], name='app_withdra_user_id_75ffbe_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['created_at'], name='app_withdra_created_5e0711_idx'),
        ),
    ]
