# Generated by Django 5.2.4 on 2025-10-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_deposit_app_deposit_user_id_180647_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deposit',
            name='app_deposit_user_id_180647_idx',
        ),
        migrations.RemoveIndex(
            model_name='deposit',
            name='app_deposit_created_b65ec9_idx',
        ),
        migrations.RemoveIndex(
            model_name='investment',
            name='app_investm_user_id_c5468e_idx',
        ),
        migrations.RemoveIndex(
            model_name='investment',
            name='app_investm_created_ba7b65_idx',
        ),
        migrations.RemoveIndex(
            model_name='withdrawal',
            name='app_withdra_user_id_75ffbe_idx',
        ),
        migrations.RemoveIndex(
            model_name='withdrawal',
            name='app_withdra_created_5e0711_idx',
        ),
    ]
