# Generated by Django 5.2.4 on 2025-10-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_deposit_app_deposit_user_id_180647_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaddress',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='wallet_qr/'),
        ),
    ]
