# Generated by Django 5.2.4 on 2025-11-09 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_paymentaddress_qr_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ('-occurred_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ('-occurred_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ('-occurred_at', '-created_at')},
        ),
        migrations.AddField(
            model_name='deposit',
            name='occurred_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investment',
            name='occurred_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='occurred_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
